-- 000100 down: intentional no-op.
--
-- The up migration NULLed every raw approval_token and kept only its SHA-256
-- digest in approval_token_hash, which cannot be reversed. Dropping
-- approval_token_hash here would destroy the only copy of every live
-- approval/revocation token, so a later re-up would permanently invalidate every
-- outstanding link. Leaving the column in place is safe for pre-#103 code
-- (it never reads the column; outstanding links fail closed as invalid, and
-- the raw tokens it writes are swept into the hash again by a re-up, which
-- uses ADD COLUMN IF NOT EXISTS). The column is removed only by the
-- follow-up contract migration.
SELECT 1;
