output "pool_name" {
  description = "Full resource name of the Workload Identity Pool"
  value       = google_iam_workload_identity_pool.cudly.name
}

output "provider_resource_name" {
  description = "Full resource name of the Workload Identity Pool Provider"
  value       = google_iam_workload_identity_pool_provider.cudly.name
}

output "project_number" {
  description = "Numeric project number (needed for the credential config)"
  value       = data.google_project.current.number
}

output "gcloud_command" {
  description = <<-EOT
    Run this command after terraform apply to generate the external account credential
    config JSON. Paste the JSON output into CUDly as gcp_workload_identity_config.
  EOT
  value = var.provider_type == "aws" ? (
    "gcloud iam workload-identity-pools create-cred-config ${google_iam_workload_identity_pool_provider.cudly.name} --service-account=${var.service_account_email} --aws --output-file=cudly-wif-config.json"
    ) : (
    "gcloud iam workload-identity-pools create-cred-config ${google_iam_workload_identity_pool_provider.cudly.name} --service-account=${var.service_account_email} --output-file=cudly-wif-config.json"
  )
}

output "cudly_account_registration" {
  description = "Values to use when registering this account in CUDly"
  value       = <<-EOT
    provider                        : gcp
    gcp_auth_mode                   : workload_identity_federation
    gcp_project_id                  : ${var.project}
    gcp_client_email (optional)     : ${var.service_account_email}
    gcp_workload_identity_config    : <paste the JSON generated by the gcloud_command output>
  EOT
}

output "registration_response" {
  description = "CUDly registration API response (contains reference_token for status checks)"
  value       = local.do_register ? data.http.cudly_registration[0].response_body : "Skipped (cudly_api_url or contact_email not set)"
  sensitive   = false
}
