// gen-permissions generates frontend/src/permissions.generated.ts from the
// backend's DefaultAdminPermissions / DefaultUserPermissions /
// DefaultReadOnlyPermissions constants in internal/auth/types.go.
//
// The generated file is imported by the hand-written
// frontend/src/permissions.ts wrapper so the small data surface that
// mirrors backend state (the three default permission sets) stays in
// lockstep with the Go source of truth. A pre-commit hook re-runs this
// binary and `git diff --exit-code` catches a stale committed file.
//
// Run from repo root:
//
//	go run ./cmd/gen-permissions
//
// Re-running produces deterministic output: entries are sorted by
// (action, resource) before emission.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/LeanerCloud/CUDly/internal/auth"
)

const outputRelPath = "frontend/src/permissions.generated.ts"

// permEntry is a sortable mirror of auth.Permission for stable emission.
type permEntry struct {
	Action   string
	Resource string
}

func collect(perms []auth.Permission) []permEntry {
	out := make([]permEntry, 0, len(perms))
	for _, p := range perms {
		out = append(out, permEntry{Action: p.Action, Resource: p.Resource})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Action != out[j].Action {
			return out[i].Action < out[j].Action
		}
		return out[i].Resource < out[j].Resource
	})
	return out
}

func render(name string, entries []permEntry, buf *bytes.Buffer) {
	fmt.Fprintf(buf, "export const %s: ReadonlySet<string> = new Set([\n", name)
	for _, e := range entries {
		fmt.Fprintf(buf, "  '%s:%s',\n", e.Action, e.Resource)
	}
	fmt.Fprintln(buf, "]);")
}

func main() {
	var buf bytes.Buffer
	buf.WriteString(`// CODE GENERATED by ` + "`go run ./cmd/gen-permissions`" + `. DO NOT EDIT MANUALLY.
//
// Source of truth: internal/auth/types.go (DefaultAdminPermissions,
// DefaultUserPermissions, DefaultReadOnlyPermissions). To regenerate after
// editing the Go defaults, run:
//
//   go run ./cmd/gen-permissions
//
// The pre-commit hook 'permissions-codegen' re-runs this generator and
// 'git diff --exit-code' on this file; CI fails if the committed copy is
// stale.
//
// Entries are sorted by (action, resource) for a stable diff. Imported
// by ./permissions.ts which adds the hand-written closed-union types and
// the canAccess / isAdmin / getRolePermissions helpers.

`)

	render("ADMIN_PERMS", collect(auth.DefaultAdminPermissions()), &buf)
	buf.WriteString("\n")
	render("USER_PERMS", collect(auth.DefaultUserPermissions()), &buf)
	buf.WriteString("\n")
	render("READONLY_PERMS", collect(auth.DefaultReadOnlyPermissions()), &buf)

	// Resolve the output path relative to the repo root. The generator is
	// always invoked from the repo root (the comment block on the package
	// documents this), so a relative path is correct. We still clean it
	// for safety.
	outPath := filepath.Clean(outputRelPath)
	// 0600 satisfies gosec G306; the file is regenerated on demand and
	// also committed to git (where git stores the blob content, not the
	// fs permission), so anyone who runs the build pipeline produces a
	// fresh local copy.
	if err := os.WriteFile(outPath, buf.Bytes(), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "gen-permissions: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("gen-permissions: wrote %s (%d bytes)\n", outPath, buf.Len())
}
