variable "subscription_id" {
  description = "Azure subscription ID where CUDly will purchase reservations."
  type        = string
}

variable "tenant_id" {
  description = "Azure AD tenant ID."
  type        = string
}

variable "app_display_name" {
  description = "Display name for the Azure AD App Registration."
  type        = string
  default     = "CUDly"
}

variable "certificate_pem" {
  description = <<-EOT
    X.509 certificate PEM string. When empty, a key pair and self-signed
    certificate are auto-generated by Terraform and sent to CUDly during
    registration. When provided, uses the given certificate (you must
    store the matching private key in CUDly manually).
  EOT
  type        = string
  sensitive   = false
  default     = ""
}

variable "cudly_api_url" {
  description = "CUDly API base URL for automatic account registration. Leave empty to skip registration."
  type        = string
  default     = ""
}

variable "account_name" {
  description = "Human-readable name for this account in CUDly."
  type        = string
  default     = ""
}

variable "contact_email" {
  description = "Contact email for registration notifications."
  type        = string
  default     = ""
}
