// CODE GENERATED by `go run ./cmd/gen-permissions`. DO NOT EDIT MANUALLY.
//
// Source of truth: internal/auth/types.go (DefaultAdminPermissions,
// DefaultUserPermissions, DefaultReadOnlyPermissions,
// DefaultPurchaserPermissions). To regenerate after editing the Go
// defaults, run:
//
//   go run ./cmd/gen-permissions
//
// The pre-commit hook 'permissions-codegen' re-runs this generator and
// 'git diff --exit-code' on this file; CI fails if the committed copy is
// stale.
//
// Entries are sorted by (action, resource) for a stable diff. Imported
// by ./permissions.ts which adds the hand-written closed-union types and
// the canAccess / isAdmin / getRolePermissions helpers.

export const ADMIN_PERMS: ReadonlySet<string> = new Set([
  'admin:*',
]);

export const USER_PERMS: ReadonlySet<string> = new Set([
  'approve-own:purchases',
  'cancel-own:purchases',
  'create:plans',
  'delete:plans',
  'retry-own:purchases',
  'revoke-own:purchases',
  'update:plans',
  'update:purchases',
  'view:history',
  'view:plans',
  'view:purchases',
  'view:recommendations',
]);

export const READONLY_PERMS: ReadonlySet<string> = new Set([
  'view:history',
  'view:plans',
  'view:recommendations',
]);

export const PURCHASER_PERMS: ReadonlySet<string> = new Set([
  'approve-any:purchases',
  'execute:purchases',
  'retry-any:purchases',
  'view:history',
  'view:plans',
  'view:purchases',
  'view:recommendations',
]);
