# SES (Simple Email Service) Configuration
# DKIM DNS records for email verification

# Data source for Route53 zone
data "aws_route53_zone" "main" {
  count = length(var.frontend_domain_names) > 0 ? 1 : 0

  name         = var.subdomain_zone_name
  private_zone = false
}

# SES DKIM verification records
# These are generated by AWS SES and need to be added to Route53 for DKIM verification
# The token values are specific to the SES domain identity

resource "aws_route53_record" "ses_dkim_1" {
  count = length(var.frontend_domain_names) > 0 ? 1 : 0

  zone_id = data.aws_route53_zone.main[0].zone_id
  name    = "ynjsclhrc44omh22xvlgaww7jk4r3oc6._domainkey.${var.subdomain_zone_name}"
  type    = "CNAME"
  ttl     = 300
  records = ["ynjsclhrc44omh22xvlgaww7jk4r3oc6.dkim.amazonses.com"]
}

resource "aws_route53_record" "ses_dkim_2" {
  count = length(var.frontend_domain_names) > 0 ? 1 : 0

  zone_id = data.aws_route53_zone.main[0].zone_id
  name    = "tdidjibxsglke4dj7isgbdoyogx4p33r._domainkey.${var.subdomain_zone_name}"
  type    = "CNAME"
  ttl     = 300
  records = ["tdidjibxsglke4dj7isgbdoyogx4p33r.dkim.amazonses.com"]
}

resource "aws_route53_record" "ses_dkim_3" {
  count = length(var.frontend_domain_names) > 0 ? 1 : 0

  zone_id = data.aws_route53_zone.main[0].zone_id
  name    = "lf6tf4cgr2tws267beqvjekfnrgiqdmi._domainkey.${var.subdomain_zone_name}"
  type    = "CNAME"
  ttl     = 300
  records = ["lf6tf4cgr2tws267beqvjekfnrgiqdmi.dkim.amazonses.com"]
}
