# ==============================================
# General Configuration
# ==============================================

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "cudly"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "aws_profile" {
  description = "AWS CLI profile to use for authentication (optional)"
  type        = string
  default     = null
}

variable "stack_name" {
  description = "Stack name (overrides project_name-environment)"
  type        = string
  default     = null
}

# ==============================================
# Compute Platform Selection
# ==============================================

variable "compute_platform" {
  description = "Compute platform to use (lambda or fargate)"
  type        = string
  default     = "lambda"

  validation {
    condition     = contains(["lambda", "fargate"], var.compute_platform)
    error_message = "Compute platform must be either 'lambda' or 'fargate'."
  }
}

variable "image_uri" {
  description = "Container image URI from ECR (optional - auto-generated by build module if not provided)"
  type        = string
  default     = ""
}

# ==============================================
# Networking Configuration
# ==============================================

variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "az_count" {
  description = "Number of availability zones"
  type        = number
  default     = 2
}

variable "enable_flow_logs" {
  description = "Enable VPC Flow Logs"
  type        = bool
  default     = false
}

variable "flow_logs_retention_days" {
  description = "VPC Flow Logs retention in days"
  type        = number
  default     = 7
}

# ==============================================
# Secrets Configuration
# ==============================================

variable "secret_recovery_window_days" {
  description = "Days to retain deleted secrets"
  type        = number
  default     = 7
}

variable "additional_secrets" {
  description = "Additional secrets to create (map keys are not sensitive)"
  type = map(object({
    description = string
    value       = string
  }))
  default = {}
}

# ==============================================
# Database Configuration
# ==============================================

variable "database_name" {
  description = "Database name"
  type        = string
  default     = "cudly"
}

variable "database_username" {
  description = "Database master username"
  type        = string
  default     = "cudly"
}

variable "database_engine_version" {
  description = "PostgreSQL version"
  type        = string
  default     = "16.4"
}

variable "database_min_capacity" {
  description = "Minimum Aurora Serverless v2 capacity (ACUs)"
  type        = number
  default     = 0.5
}

variable "database_max_capacity" {
  description = "Maximum Aurora Serverless v2 capacity (ACUs)"
  type        = number
  default     = 1.0
}

variable "database_backup_retention_days" {
  description = "Number of days to retain backups"
  type        = number
  default     = 7
}

variable "database_backup_window" {
  description = "Preferred backup window (UTC)"
  type        = string
  default     = "03:00-04:00"
}

variable "database_maintenance_window" {
  description = "Preferred maintenance window (UTC)"
  type        = string
  default     = "sun:04:00-sun:05:00"
}

variable "database_cloudwatch_logs" {
  description = "CloudWatch log types to enable"
  type        = list(string)
  default     = ["postgresql"]
}

variable "database_performance_insights" {
  description = "Enable Performance Insights"
  type        = bool
  default     = false
}

variable "database_deletion_protection" {
  description = "Enable deletion protection"
  type        = bool
  default     = false # False in dev for easy teardown
}

variable "database_skip_final_snapshot" {
  description = "Skip final snapshot on deletion"
  type        = bool
  default     = true # True in dev for easy teardown
}

variable "database_auto_migrate" {
  description = "Automatically run migrations on Lambda cold start"
  type        = bool
  default     = true
}

variable "additional_database_allowed_cidrs" {
  description = "Additional CIDR blocks allowed to access database"
  type        = list(string)
  default     = []
}

variable "admin_email" {
  description = "Email address for the default admin user"
  type        = string
}

# ==============================================
# Lambda Configuration
# ==============================================

variable "lambda_architecture" {
  description = "Lambda architecture (x86_64 or arm64)"
  type        = string
  default     = "arm64"
}

variable "lambda_memory_size" {
  description = "Lambda memory size in MB"
  type        = number
  default     = 512
}

variable "lambda_timeout" {
  description = "Lambda timeout in seconds"
  type        = number
  default     = 30
}

variable "lambda_enable_function_url" {
  description = "Enable Lambda Function URL"
  type        = bool
  default     = true
}

variable "lambda_function_url_auth_type" {
  description = "Function URL auth type (NONE or AWS_IAM)"
  type        = string
  default     = "NONE"
}

variable "lambda_allowed_origins" {
  description = "CORS allowed origins"
  type        = list(string)
  default     = ["*"]
}

variable "lambda_reserved_concurrency" {
  description = "Reserved concurrent executions (-1 for unreserved)"
  type        = number
  default     = -1
}

variable "lambda_log_retention_days" {
  description = "CloudWatch log retention in days"
  type        = number
  default     = 7
}

# ==============================================
# Scheduled Tasks Configuration
# ==============================================

variable "enable_scheduled_tasks" {
  description = "Enable scheduled EventBridge tasks"
  type        = bool
  default     = true
}

variable "recommendation_schedule" {
  description = "Schedule expression for recommendation collection"
  type        = string
  default     = "rate(1 day)"
}

# ==============================================
# Additional Configuration
# ==============================================

variable "additional_env_vars" {
  description = "Additional environment variables for Lambda"
  type        = map(string)
  default     = {}
}

# ==============================================
# Fargate Configuration
# ==============================================

variable "fargate_cpu" {
  description = "Fargate CPU units (256, 512, 1024, 2048, 4096)"
  type        = number
  default     = 512
}

variable "fargate_memory" {
  description = "Fargate memory in MB"
  type        = number
  default     = 1024
}

variable "fargate_desired_count" {
  description = "Desired number of Fargate tasks"
  type        = number
  default     = 2
}

variable "fargate_min_capacity" {
  description = "Minimum capacity for auto-scaling"
  type        = number
  default     = 1
}

variable "fargate_max_capacity" {
  description = "Maximum capacity for auto-scaling"
  type        = number
  default     = 10
}

variable "fargate_enable_https" {
  description = "Enable HTTPS on Fargate ALB"
  type        = bool
  default     = false
}

variable "fargate_certificate_arn" {
  description = "ARN of ACM certificate for Fargate ALB HTTPS"
  type        = string
  default     = ""
}

variable "fargate_enable_execute_command" {
  description = "Enable ECS Exec for debugging"
  type        = bool
  default     = false
}

# ==============================================
# Frontend Configuration
# ==============================================

variable "enable_frontend_build" {
  description = "Enable frontend build and deployment"
  type        = bool
  default     = false
}

variable "frontend_domain_names" {
  description = "Custom domain names for the frontend CloudFront distribution"
  type        = list(string)
  default     = []
}

variable "frontend_acm_certificate_arn" {
  description = "ARN of ACM certificate for custom frontend domain (must be in us-east-1)"
  type        = string
  default     = null
}

variable "frontend_route53_zone_id" {
  description = "Route53 hosted zone ID for frontend DNS record"
  type        = string
  default     = null
}

variable "frontend_price_class" {
  description = "CloudFront price class (PriceClass_All, PriceClass_200, PriceClass_100)"
  type        = string
  default     = "PriceClass_100"
}

variable "frontend_waf_acl_arn" {
  description = "ARN of WAF Web ACL to associate with frontend CloudFront"
  type        = string
  default     = ""
}

variable "subdomain_zone_name" {
  description = "Subdomain zone name to create (e.g., cudly.leanercloud.com). Leave empty to skip zone creation."
  type        = string
  default     = ""
}

variable "create_subdomain_zone" {
  description = "Whether to create the subdomain zone. Set to false to use existing zone managed elsewhere."
  type        = bool
  default     = false
}

variable "enable_docker_build" {
  description = "Enable Docker build module (builds and pushes image during terraform apply). Set to false to use pre-built image_uri instead."
  type        = bool
  default     = true
}
