# ==============================================
# General Configuration
# ==============================================

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "cudly"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "aws_profile" {
  description = "AWS CLI profile to use for authentication (optional)"
  type        = string
  default     = null
}

variable "stack_name" {
  description = "Stack name (overrides project_name-environment)"
  type        = string
  default     = null
}

# ==============================================
# Compute Platform Selection
# ==============================================

variable "compute_platform" {
  description = "Compute platform to use (lambda or fargate)"
  type        = string
  default     = "lambda"

  validation {
    condition     = contains(["lambda", "fargate"], var.compute_platform)
    error_message = "Compute platform must be either 'lambda' or 'fargate'."
  }
}

variable "image_uri" {
  description = "Container image URI from ECR (optional - auto-generated by build module if not provided)"
  type        = string
  default     = ""
}

# ==============================================
# Networking Configuration
# ==============================================

variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "az_count" {
  description = "Number of availability zones"
  type        = number
  default     = 2
}

variable "enable_flow_logs" {
  description = <<-EOT
    Enable VPC Flow Logs. Default is true so every environment captures a
    network audit trail by default. Override to false in cost-sensitive dev
    environments — VPC Flow Logs ingest into CloudWatch and incur per-GB
    charges (see flow_logs_retention_days).
  EOT
  type        = bool
  default     = true
}

variable "flow_logs_retention_days" {
  description = "VPC Flow Logs retention in days"
  type        = number
  default     = 7
}

# ==============================================
# Secrets Configuration
# ==============================================

variable "secret_recovery_window_days" {
  description = "Days to retain deleted secrets"
  type        = number
  default     = 7
}

variable "additional_secrets" {
  description = "Additional secrets to create (map keys are not sensitive)"
  type = map(object({
    description = string
    value       = string
  }))
  default = {}
}

# ==============================================
# Database Configuration
# ==============================================

variable "database_name" {
  description = "Database name"
  type        = string
  default     = "cudly"
}

variable "database_username" {
  description = "Database master username"
  type        = string
  default     = "cudly"
}

variable "database_engine_version" {
  description = "PostgreSQL version"
  type        = string
  default     = "16.6"
}

variable "database_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t4g.micro"
}

variable "database_allocated_storage" {
  description = "Initial allocated storage in GB"
  type        = number
  default     = 20
}

variable "database_max_allocated_storage" {
  description = "Maximum allocated storage in GB for autoscaling (0 to disable)"
  type        = number
  default     = 100
}

variable "database_backup_retention_days" {
  description = "Number of days to retain backups"
  type        = number
  default     = 7
}

variable "database_performance_insights" {
  description = "Enable Performance Insights"
  type        = bool
  default     = false
}

variable "database_deletion_protection" {
  description = "Enable deletion protection"
  type        = bool
  default     = true
}

variable "database_skip_final_snapshot" {
  description = <<-EOT
    Skip final snapshot when the RDS instance is destroyed. Default is false
    so production destroys preserve a recoverable snapshot. Override to true
    in dev tfvars when teardown ergonomics matter more than recoverability.
  EOT
  type        = bool
  default     = false
}

variable "database_auto_migrate" {
  description = "Automatically run migrations on Lambda cold start"
  type        = bool
  default     = true
}

variable "admin_email" {
  description = "Email address for the default admin user"
  type        = string
}

variable "admin_password" {
  description = "Optional initial admin password (skips password reset requirement)"
  type        = string
  default     = null
  sensitive   = true
}

# ==============================================
# Lambda Configuration
# ==============================================

variable "lambda_architecture" {
  description = "Lambda/Fargate CPU architecture (arm64 or x86_64). Empty string auto-detects from the builder host."
  type        = string
  default     = ""

  validation {
    condition     = contains(["arm64", "x86_64", ""], var.lambda_architecture)
    error_message = "lambda_architecture must be 'arm64', 'x86_64', or '' (auto-detect)."
  }
}

variable "lambda_memory_size" {
  description = "Lambda memory size in MB"
  type        = number
  default     = 512
}

variable "lambda_timeout" {
  description = "Lambda timeout in seconds"
  type        = number
  default     = 30
}

variable "lambda_enable_function_url" {
  description = "Enable Lambda Function URL"
  type        = bool
  default     = true
}

variable "lambda_function_url_auth_type" {
  description = <<-EOT
    Lambda Function URL auth type — must be "NONE" or "AWS_IAM". Default is
    "NONE" because CUDly is a browser-served SPA that talks directly to the
    Function URL; the browser cannot SigV4-sign requests. Auth is enforced at
    the application layer (login session, JWT, API keys, CSRF) — see
    internal/api/handler_login.go and middleware in router.go. Override to
    AWS_IAM only when fronting the URL with a signed-request gateway
    (CloudFront with Lambda@Edge, API Gateway, etc.).
  EOT
  type        = string
  default     = "NONE"

  validation {
    condition     = contains(["AWS_IAM", "NONE"], var.lambda_function_url_auth_type)
    error_message = "lambda_function_url_auth_type must be either \"AWS_IAM\" or \"NONE\"."
  }
}

variable "lambda_allowed_origins" {
  description = "CORS allowed origins"
  type        = list(string)
  default     = []
}

variable "lambda_reserved_concurrency" {
  description = "Reserved concurrent executions (-1 for unreserved)"
  type        = number
  default     = -1
}

variable "lambda_log_retention_days" {
  description = "CloudWatch log retention in days"
  type        = number
  default     = 7
}

# ==============================================
# Scheduled Tasks Configuration
# ==============================================

variable "enable_scheduled_tasks" {
  description = "Enable scheduled EventBridge tasks"
  type        = bool
  default     = true
}

variable "recommendation_schedule" {
  description = "Schedule expression for recommendation collection"
  type        = string
  default     = "rate(1 day)"
}

variable "enable_ri_exchange_schedule" {
  description = "Enable scheduled RI exchange automation"
  type        = bool
  default     = false
}

variable "ri_exchange_schedule" {
  description = "Schedule for RI exchange automation. rate() starts from deployment time; cron(0 0/6 * * ? *) runs at fixed clock hours (EventBridge cron syntax). For predictable approval windows, prefer cron."
  type        = string
  default     = "rate(6 hours)"
}

# ==============================================
# Multi-Account Configuration
# ==============================================

variable "credential_encryption_key" {
  description = "AES-256-GCM key for account credential encryption (64-char hex = 32 bytes). Auto-generated if empty."
  type        = string
  sensitive   = true
  default     = ""
}

variable "max_account_parallelism" {
  description = "Maximum number of cloud accounts to process in parallel during plan fan-out"
  type        = number
  default     = 10
}

# ==============================================
# Additional Configuration
# ==============================================

variable "additional_env_vars" {
  description = "Additional environment variables for Lambda"
  type        = map(string)
  default     = {}
}

# ==============================================
# Fargate Configuration
# ==============================================

variable "fargate_cpu" {
  description = "Fargate CPU units (256, 512, 1024, 2048, 4096)"
  type        = number
  default     = 512
}

variable "fargate_memory" {
  description = "Fargate memory in MB"
  type        = number
  default     = 1024
}

variable "fargate_desired_count" {
  description = "Desired number of Fargate tasks"
  type        = number
  default     = 2
}

variable "fargate_min_capacity" {
  description = "Minimum capacity for auto-scaling"
  type        = number
  default     = 1
}

variable "fargate_max_capacity" {
  description = "Maximum capacity for auto-scaling"
  type        = number
  default     = 10
}

variable "fargate_certificate_arn" {
  description = "ARN of ACM certificate for Fargate ALB HTTPS"
  type        = string
  default     = ""
}

variable "fargate_enable_execute_command" {
  description = "Enable ECS Exec for debugging"
  type        = bool
  default     = false
}

# ==============================================
# Frontend Configuration
# ==============================================

variable "enable_cdn" {
  description = "Enable CDN (CloudFront) for custom domain and edge caching. When false, the compute endpoint serves the frontend directly. Only needed when using custom domains."
  type        = bool
  default     = false
}

variable "frontend_domain_names" {
  description = "Custom domain names for the frontend CloudFront distribution"
  type        = list(string)
  default     = []
}

variable "frontend_acm_certificate_arn" {
  description = "ARN of ACM certificate for custom frontend domain (must be in us-east-1)"
  type        = string
  default     = null
}

variable "frontend_route53_zone_id" {
  description = "Route53 hosted zone ID for frontend DNS record"
  type        = string
  default     = null
}

variable "frontend_price_class" {
  description = "CloudFront price class (PriceClass_All, PriceClass_200, PriceClass_100)"
  type        = string
  default     = "PriceClass_100"
}

variable "frontend_waf_acl_arn" {
  description = "ARN of WAF Web ACL to associate with frontend CloudFront"
  type        = string
  default     = ""
}

variable "subdomain_zone_name" {
  description = "Subdomain zone name to create (e.g., cudly.leanercloud.com). Leave empty to skip zone creation."
  type        = string
  default     = ""
}

variable "create_subdomain_zone" {
  description = "Whether to create the subdomain zone. Set to false to use existing zone managed elsewhere."
  type        = bool
  default     = false
}

variable "enable_docker_build" {
  description = "Enable Docker build module (builds and pushes image during terraform apply). Set to false to use pre-built image_uri instead."
  type        = bool
  default     = true
}
